/*BLACK FRIDAY SALES DATA*/

/*DATA PREPARATION*/
/*We will create a library for the dataset available in .csv format*/
LIBNAME FRIDAY "C:\USERS\KMAMGAIN\DESKTOP\PROJECT DATA FILES\PROJECT DATA FILES\10. BLACK FRIDAY DATA";

/*IMPORT TRAIN DATA*/
PROC IMPORT
DATAFILE="C:\USERS\KMAMGAIN\DESKTOP\PROJECT DATA FILES\PROJECT DATA FILES\10. BLACK FRIDAY DATA\TRAIN.CSV" 
DBMS=CSV
OUT=FRIDAY.MYDATA
REPLACE;

GETNAMES=YES;
RUN;


/**************************************************************************************/
/**************************************************************************************/
/**************************************************************************************/
/*CREATING NEW TABLES*/


PROC SQL;
CREATE TABLE DIST_COUNT AS
SELECT GENDER, CITY_CATEGORY, COUNT(DISTINCT USER_ID) AS TOTAL_CUST,
		COUNT(DISTINCT PRODUCT_ID) AS DIST_PRODS
FROM TEST
GROUP BY CITY_CATEGORY, GENDER;
QUIT;


/*PURCHASE PER CUSTOMER*/
PROC SQL;
CREATE TABLE UNQ_CUST AS
SELECT DISTINCT USER_ID,
				GENDER,
				AGE,
				OCCUPATION,
				MARITAL_STATUS,
				CITY_CATEGORY,
				STAY_IN_CURRENT_CITY_YEARS
FROM TEST
;
QUIT;
PROC SQL;
CREATE TABLE CUST_PUR AS
SELECT USER_ID, 
	   SUM(PURCHASE) AS TOTAL_AMT,
	   COUNT(PRODUCT_CATEGORY_1) AS TOTAL_PRODS
FROM TEST
GROUP BY USER_ID;
QUIT;

PROC SQL;
CREATE TABLE AGGRE AS
SELECT *
FROM CUST_PUR C
JOIN UNQ_CUST U
ON C.USER_ID = U.USER_ID;
QUIT;


/**************************************************************************************/
/**************************************************************************************/
/**************************************************************************************/
/*PRESENTATION 1. INTRODUCTION - METHODOLOGY*/
TITLE "EXPLORE THE BLACK FRIDAY DATA";
PROC CONTENTS DATA = FRIDAY.MYDATA;
RUN;

/*OBSERVATIONS*/
PROC PRINT DATA=FRIDAY.MYDATA (OBS=2) NOOBS LABEL ; RUN; 

TITLE 'MISSING VALUE IN ALL VARIABLES';
/* CREATE A FORMAT TO GROUP MISSING AND NONMISSING */
PROC FORMAT;
 VALUE $MISSFMT ' '='MISSING' OTHER='NOT MISSING';
 VALUE  MISSFMT  . ='MISSING' OTHER='NOT MISSING';
RUN;
 
PROC FREQ DATA=FRIDAY.MYDATA; 
FORMAT _CHAR_ $MISSFMT.; /* APPLY FORMAT FOR THE DURATION OF THIS PROC */
TABLES _CHAR_ / MISSING MISSPRINT NOCUM NOPERCENT;
FORMAT _NUMERIC_ MISSFMT.;
TABLES _NUMERIC_ / MISSING MISSPRINT NOCUM NOPERCENT;
RUN;

/*UNIVARIATE ANALYSIS*/
DATA FRIDAY.CLEAN;
SET FRIDAY.MYDATA;
DROP PRODUCT_CATEGORY_3
RETAIN _PRODUCT_CATEGORY_2;
IF NOT MISSING(PRODUCT_CATEGORY_2) THEN _PRODUCT_CATEGORY_2=PRODUCT_CATEGORY_2;
ELSE PRODUCT_CATEGORY_2=PRODUCT_CATEGORY_1;
DROP _PRODUCT_CATEGORY_2;
RUN;

DATA TEST;
SET FRIDAY.CLEAN;
DIST_PROD = CATX('-',PRODUCT_CATEGORY_1, PRODUCT_CATEGORY_2);
RUN;


/**************************************************************************************/
/**************************************************************************************/
/**************************************************************************************/

/*SLIDE 8 PURCHASE DISTRIBUTION*/
PROC SGPLOT DATA = TEST;
TITLE "PURCHASE DISTIBUTION";
FOOTNOTE "CREATED BY KSHITIJ MAMGAIN";
HISTOGRAM PURCHASE /NBINS =20;
DENSITY PURCHASE / TYPE = KERNEL;
RUN;

/*3 PANEL QUANTILE*/

/* DEFINE 'THREEPANEL' TEMPLATE THAT DISPLAYS A HISTOGRAM, BOX PLOT, AND Q-Q PLOT */
PROC TEMPLATE;
DEFINE STATGRAPH THREEPANEL;
DYNAMIC _X _QUANTILE _TITLE _MU _SIGMA;
BEGINGRAPH;
   ENTRYTITLE HALIGN=CENTER _TITLE;
   LAYOUT LATTICE / ROWDATARANGE=DATA COLUMNDATARANGE=UNION 
      COLUMNS=1 ROWGUTTER=5 ROWWEIGHTS=(0.4 0.10 0.5);
      LAYOUT OVERLAY;
         HISTOGRAM   _X / NAME='HISTOGRAM' BINAXIS=FALSE;
         DENSITYPLOT _X / NAME='NORMAL' NORMAL();
         DENSITYPLOT _X / NAME='KERNEL' KERNEL() LINEATTRS=GRAPHDATA2(THICKNESS=2 );
         DISCRETELEGEND 'NORMAL' 'KERNEL' / BORDER=TRUE HALIGN=RIGHT VALIGN=TOP LOCATION=INSIDE ACROSS=1;
      ENDLAYOUT;
      LAYOUT OVERLAY;
         BOXPLOT Y=_X / BOXWIDTH=0.8 ORIENT=HORIZONTAL;
      ENDLAYOUT;
      LAYOUT OVERLAY;
         SCATTERPLOT X=_X Y=_QUANTILE;
         LINEPARM X=_MU Y=0.0 SLOPE=EVAL(1./_SIGMA) / EXTEND=TRUE CLIP=TRUE;
      ENDLAYOUT;
      COLUMNAXES;
         COLUMNAXIS;
      ENDCOLUMNAXES;
   ENDLAYOUT;
ENDGRAPH;
END;
RUN;

/* MACRO TO CREATE A THREE-PANEL DISPLAY THAT SHOWS THE 
   DISTRIBUTION OF DATA AND COMPARES THE DISTRIBUTION TO A NORMAL
   DISTRIBUTION. THE ARGUMENTS ARE 
   DSNAME = NAME OF SAS DATA SET
   VAR    = NAME OF VARIABLE IN THE DATA SET.
   THE MACRO CALLS THE SGRENDER PROCEDURE TO PRODUCE A PLOT
   THAT IS DEFINED BY THE 'THREEPANEL' TEMPLATE. THE PLOT INCLUDES
   1) A HISTOGRAM WITH A NORMAL AND KERNEL DENSITY OVERLAY
   2) A BOX PLOT
   3) A NORMAL Q-Q PLOT

   EXAMPLE CALLING SEQUENCE:
   ODS GRAPHICS ON;
   %THREEPANEL(SASHELP.CARS, MPG_CITY)
   %THREEPANEL(SASHELP.IRIS, SEPALLENGTH)

   FOR DETAILS, SEE
   HTTP://BLOGS.SAS.COM/CONTENT/IML/2013/05/08/THREE-PANEL-VISUALIZATION/
*/
%MACRO THREEPANEL(DSNAME, VAR);
   %LOCAL MU SIGMA;

   /* 1. SORT COPY OF DATA */
   PROC SORT DATA=&DSNAME OUT=_MYDATA(KEEP=&VAR);
      BY &VAR;
   RUN;

   /* 2. USE PROC UNIVARIATE TO CREATE Q-Q PLOT 
         AND PARAMETER ESTIMATES */
   ODS EXCLUDE ALL;
   PROC UNIVARIATE DATA=_MYDATA;
      VAR &VAR;
      HISTOGRAM &VAR / NORMAL; /* CREATE PARAMETERESTIMATES TABLE */
      QQPLOT    &VAR / NORMAL; 
      ODS OUTPUT PARAMETERESTIMATES=_PE QQPLOT=_QQ(KEEP=QUANTILE DATA RENAME=(DATA=&VAR));
   RUN;
   ODS EXCLUDE NONE;

   /* 3. MERGE QUANTILES WITH DATA */
   DATA _MYDATA;
   MERGE _MYDATA _QQ;
   LABEL QUANTILE = "NORMAL QUANTILE";
   RUN;

   /* 4. GET PARAMETER ESTIMATES INTO MACRO VARS */
   DATA _NULL_;
   SET _PE;
   IF SYMBOL="MU"    THEN CALL SYMPUTX("MU", ESTIMATE);
   IF SYMBOL="SIGMA" THEN CALL SYMPUTX("SIGMA", ESTIMATE);
   RUN;

   PROC SGRENDER DATA=_MYDATA TEMPLATE=THREEPANEL;
   DYNAMIC _X="&VAR" _QUANTILE="QUANTILE" _MU="&MU" _SIGMA="&SIGMA"
          _TITLE="DISTRIBUTION OF &VAR";
   RUN;
%MEND;
ODS GRAPHICS ON;
%THREEPANEL(WORK.TEST, PURCHASE)

/*SLIDE 9 PURCHASE DISTRIBUTION BOX PLOT*/
PROC SGPLOT DATA = PROD_DISTR;
TITLE "CITY WISE AVERAGE SALES AMOUNT PER PRODUCT";
FOOTNOTE "CREATED BY KSHITIJ MAMGAIN";
VBOX AVG_SALES / GROUP = CITY_CATEGORY GROUPDISPLAY=CLUSTER ;

RUN;
QUIT;


/**************************************************************************************/
/**************************************************************************************/
/**************************************************************************************/

/*SLIDE 10 CUSTOMER DISTRIBUTION IN TABULAR FORM TO 
IDENTIFY THE DOMINANT CUSTOMERS*/
PROC TABULATE DATA=TEST;
TITLE 'DISTRIBUTIONS OF CUSTOMERS';
CLASS AGE CITY_CATEGORY GENDER;

TABLE CITY_CATEGORY*(GENDER ALL), AGE='AGE GROUPS'*(PCTN='% ') ALL*(N PCTN);
RUN;


/**************************************************************************************/
/**************************************************************************************/
/**************************************************************************************/
/*SLIDE 11 CUSTOMER DISTRIBUTION ACCORDING TO THE GENDER*/

/*PART 1 BAR CHART*/
PROC SGPLOT DATA = TEST;
TITLE "GENDER WISE CUSTOMER DISTRIBUTION";
FOOTNOTE "CREATED BY KSHITIJ MAMGAIN";
VBAR CITY_CATEGORY / GROUP = GENDER GROUPDISPLAY=CLUSTER ;

RUN;
QUIT;

/* PART 2 DONUT CHART FOR GENDER-WISE DISTRIBUTION IN
	DIFFERENT CITIES */
TITLE 'SALES BY GENDER IN DIFFERENT CITY CATEGORIES';

LEGEND1 LABEL=NONE
        SHAPE=BAR(4,1.5)
        POSITION=(MIDDLE LEFT)
        OFFSET=(5,)
        ACROSS=1
        MODE=SHARE;

 /* GENERATE DONUT CHART */
PROC GCHART DATA=TEST;
   DONUT GENDER/ SUMVAR=PURCHASE
                SUBGROUP=CITY_CATEGORY
                NOHEADING
                DONUTPCT=30
                LABEL=('BLACK' JUSTIFY=CENTER 'FRIDAY')
                LEGEND=LEGEND1
                COUTLINE=BLACK
                CTEXT=BLACK;
RUN;
QUIT;

/*PART 3 TABLE FOR GENDER WISE DISTRIBUTION*/
PROC TABULATE DATA=DIST_COUNT;
TITLE 'CUSTOMER COUNT IN CITY CATEGORIES';
CLASS CITY_CATEGORY GENDER;
VAR TOTAL_CUST;
TABLE CITY_CATEGORY ALL ,GENDER *(TOTAL_CUST=' ');
RUN;

/**************************************************************************************/
/**************************************************************************************/
/**************************************************************************************/
/*SLIDE 12 GENDER WISE ANALYSIS*/
/*PART 1 OCCUPATION - WISE GENDER DISTRIBUTION*/

TITLE 'SALES BY GENDER IN DIFFERENT OCCUPATION';

LEGEND1 LABEL=NONE
        SHAPE=BAR(4,1.5)
        POSITION=(MIDDLE LEFT)
        OFFSET=(5,)
        ACROSS=1
        MODE=SHARE;

 /* GENERATE DONUT CHART */
PROC GCHART DATA=TEST;
   DONUT OCCUPATION/ SUMVAR=PURCHASE
                SUBGROUP=GENDER
                NOHEADING
                DONUTPCT=30
				PERCENT = INSIDE
                LABEL=('BLACK' JUSTIFY=CENTER 'FRIDAY')
                LEGEND=LEGEND1
                COUTLINE=BLACK
                CTEXT=BLACK;
RUN;
QUIT;


/*PART 2 */

TITLE 'SALES BY GENDER FOR DIFFERENT PRODUCTS';

LEGEND1 LABEL=NONE
        SHAPE=BAR(4,1.5)
        POSITION=(MIDDLE LEFT)
        OFFSET=(5,)
        ACROSS=1
        MODE=SHARE;

 /* GENERATE DONUT CHART */
PROC GCHART DATA=TEST;
   DONUT DIST_PROD/ SUMVAR=PURCHASE
                SUBGROUP=GENDER
                NOHEADING
                DONUTPCT=30
				PERCENT = INSIDE
                LABEL=('BLACK' JUSTIFY=CENTER 'FRIDAY')
                LEGEND=LEGEND1
                COUTLINE=BLACK
                CTEXT=BLACK;
RUN;
QUIT;



/**************************************************************************************/
/**************************************************************************************/
/**************************************************************************************/
/*SLIDE 13 CITY CATEGORY WISE ANALYSIS*/
/*PART 1 DONUT CHART FOR PRODUCT DISTRIBUTION*/

TITLE 'SALES BY CITY CATEGORY FOR DIFFERENT PRODUCTS';

LEGEND1 LABEL=NONE
        SHAPE=BAR(4,1.5)
        POSITION=(MIDDLE LEFT)
        OFFSET=(5,)
        ACROSS=1
        MODE=SHARE;

 /* GENERATE DONUT CHART */
PROC GCHART DATA=TEST;
   DONUT DIST_PROD/ SUMVAR=PURCHASE
                SUBGROUP=CITY_CATEGORY
                NOHEADING
                DONUTPCT=30
				PERCENT = INSIDE
                LABEL=('BLACK' JUSTIFY=CENTER 'FRIDAY')
                LEGEND=LEGEND1
                COUTLINE=BLACK
                CTEXT=BLACK;
RUN;
QUIT;

/*PART 2 CLUSTERED BAR CHART*/

/*HIGHEST SPENDERS*/

/* OPEN THE LISTING DESTINATION AND ASSIGN THE LISTING STYLE TO THE GRAPH */
ODS LISTING STYLE=LISTING;
ODS GRAPHICS / WIDTH=5IN HEIGHT=2.81IN;

TITLE 'TOP PRODUCT SALES BY NUMBER OF CUSTOMERS IN CITY CATEGORIES';
PROC SGPLOT DATA=PROD_DISTR(WHERE =(DIST_PROD = '1-15' OR DIST_PROD = '1-2' 
									OR DIST_PROD = '5-5' OR DIST_PROD = '5-8'
									OR DIST_PROD = '8-8'OR DIST_PROD = '6-8'));
  VBAR CITY_CATEGORY / RESPONSE=NUMBER_OF_CUST GROUP=DIST_PROD GROUPDISPLAY=CLUSTER 
    STAT=MEAN DATASKIN=GLOSS;
  XAXIS DISPLAY=(NOLABEL NOTICKS);
  YAXIS GRID;
RUN;


/**************************************************************************************/
/**************************************************************************************/
/**************************************************************************************/
/*SLIDE 17 HYPOTHESIS TESTING*/
/*PART1 CHI SQUARE TESTING FOR CATEGORICAL VS CATEGORICAL FEATURES*/

PROC FREQ DATA = TEST;
	TABLE AGE * STAY_IN_CURRENT_CITY_YEARS / EXPECTED CHISQ NOPERCENT NOROW NOCOL;
	
	TITLE 'CONTINGENCY TABLE FOR STAY IN CITY AND AGE';
RUN;

PROC FREQ DATA = WORK.TEST;
	TABLE DIST_PROD * CITY_CATEGORY / EXPECTED CHISQ NOPERCENT NOROW NOCOL;
	
	TITLE '';
RUN;

PROC FREQ DATA = AGGRE;
	TABLE AGE * GENDER / EXPECTED CHISQ NOPERCENT NOROW NOCOL;
	
	TITLE 'CONTINGENCY TABLE FOR GENDER AND AGE';
RUN;

PROC FREQ DATA = AGGRE;
	TABLE OCCUPATION * GENDER / EXPECTED CHISQ NOPERCENT NOROW NOCOL;
	
	TITLE 'CONTINGENCY TABLE FOR GENDER AND OCCUPATION';
RUN;

PROC FREQ DATA = AGGRE;
	TABLE OCCUPATION * AGE / EXPECTED CHISQ NOPERCENT NOROW NOCOL;
	
	TITLE 'CONTINGENCY TABLE FOR OCCUPATION AND AGE';
RUN;

/*PART 2 ANVOVA ANALYSIS FOR CATEGORICAL VS CONTINUOUS VARIABLE*/

PROC ANOVA DATA = TEST;
CLASS MARITAL_STATUS;
MODEL PURCHASE = MARITAL_STATUS;
RUN;
QUIT;


/*SUMMARY TABLE*/
PROC ANOVA DATA = AGGRE;
CLASS GENDER;
MODEL TOTAL_AMT = GENDER;
RUN;
QUIT;

PROC ANOVA DATA = AGGRE;
CLASS STAY_IN_CURRENT_CITY_YEARS;
MODEL TOTAL_AMT = STAY_IN_CURRENT_CITY_YEARS;
RUN;
QUIT;

PROC ANOVA DATA = AGGRE;
CLASS AGE;
MODEL TOTAL_AMT = AGE;
RUN;
QUIT;

PROC ANOVA DATA = AGGRE;
CLASS OCCUPATION;
MODEL TOTAL_AMT = OCCUPATION;
RUN;
QUIT;

PROC ANOVA DATA = AGGRE;
CLASS MARITAL_STATUS;
MODEL TOTAL_AMT = MARITAL_STATUS;
RUN;
QUIT;


PROC ANOVA DATA = TEST;
CLASS DIST_PROD;
MODEL PURCHASE = DIST_PROD;
RUN;
QUIT;

PROC ANOVA DATA = TEST;
CLASS PRODUCT_ID;
MODEL PURCHASE = PRODUCT_ID;
RUN;
QUIT;

/*ANOVA FOR CUSTOMERS IN AGGRE TABLE*/
/*STAY_IN_CURRENT_CITY_YEARS*/
/*CREATING A MACRO FOR FASTER COMPUTATION*/

%MACRO PVAL(DATATABLE, CLASL_1, MODEL_L) 
;


PROC ANOVA DATA = &DATATABLE;
CLASS &CLASL_1;
MODEL &MODEL_L = &CLASL_1;
RUN;
QUIT;
%MEND;

%PVAL(WORK.AGGRE,STAY_IN_CURRENT_CITY_YEARS, TOTAL_AMT);
%PVAL(WORK.AGGRE,CITY_CATEGORY, TOTAL_AMT);
%PVAL(WORK.AGGRE,GENDER, TOTAL_AMT);
%PVAL(WORK.AGGRE,AGE, TOTAL_AMT);
%PVAL(WORK.AGGRE,MARITAL_STATUS, TOTAL_AMT);
%PVAL(WORK.AGGRE,AGE, OCCUPATION);


/*ANALYSIS FOR PRODUCT DISTRIBUTION*/

%PVAL(WORK.PROD_DISTR,DIST_PROD, NUMBER_OF_CUST);
%PVAL(WORK.PROD_DISTR,DIST_PROD, AVG_SALES);



/*BY MARITAL STATUS*/
PROC UNIVARIATE DATA=TEST;
  CLASS MARITAL_STATUS;
  VAR PURCHASE;      /* COMPUTES DESCRIPTIVE STATISITCS */
  HISTOGRAM PURCHASE / NORMAL MIDPOINTS=(250 TO 25000 BY 2500) NROWS=2 ODSTITLE="PURCHASE DISTRIBUTION BY MARITAL STATUS";
  ODS SELECT HISTOGRAM; /* DISPLAY ON THE HISTOGRAMS */
RUN;
QUIT;


/*PART 3 CORREALTION FOR CONTINUOS FEATURES*/
/*CONTINUOUS CORRELATION*/

PROC CORR DATA = AGGRE;
 VAR TOTAL_PRODS;
 WITH TOTAL_AMT; 
RUN;

PROC CORR DATA = PROD_DISTR;
 VAR NUMBER_OF_CUST;
 WITH AVG_SALES; 
RUN;


/**************************************************************************************/
/**************************************************************************************/
/**************************************************************************************/
/*SLIDE 18 REGRESSION MODEL*/
/*DATA TRANSFORMATION */

/*REGRESSION FOR AGGREGATED DATA*/
DATA REGRES_ (DROP = GENDER STAY_IN_CURRENT_CITY_YEARS CITY_CATEGORY AGE);
SET AGGRE;
IF GENDER = 'M' THEN SEX = 0;
ELSE SEX = 1;

IF STAY_IN_CURRENT_CITY_YEARS = '4+' THEN YEARS = 4;
ELSE IF STAY_IN_CURRENT_CITY_YEARS = '3' THEN YEARS = 3;
ELSE IF STAY_IN_CURRENT_CITY_YEARS = '2' THEN YEARS = 2;
ELSE IF STAY_IN_CURRENT_CITY_YEARS = '1' THEN YEARS = 1;
ELSE YEARS = 0;

IF CITY_CATEGORY = 'A' THEN CITY_CATEGORY_A = 1;
ELSE CITY_CATEGORY_A =0;
IF CITY_CATEGORY = 'B' THEN CITY_CATEGORY_B = 1;
ELSE CITY_CATEGORY_B =0;
IF CITY_CATEGORY = 'B' THEN CITY_CATEGORY_C = 1;
ELSE CITY_CATEGORY_C =0;

IF AGE = '0-17' THEN MEDIAN_AGE = 16; 
ELSE IF AGE = '18-25' THEN MEDIAN_AGE = 23;
ELSE IF AGE = '26-35' THEN MEDIAN_AGE = 30;
ELSE IF AGE = '36-45' THEN MEDIAN_AGE = 40;
ELSE IF AGE = '46-50' THEN MEDIAN_AGE = 48;
ELSE IF AGE = '51-55' THEN MEDIAN_AGE = 53;
ELSE MEDIAN_AGE = 60;
RUN;

PROC GLM DATA = REGRES_;
  CLASS OCCUPATION;
  MODEL TOTAL_AMT
      = SEX CITY_CATEGORY_A CITY_CATEGORY_B MEDIAN_AGE / SOLUTION SS3;
  MANOVA H=_ALL_;
RUN;
QUIT;

PROC REG DATA=REGRES_;
  MODEL TOTAL_AMT = SEX ;
  PLOT TOTAL_AMT * SEX ;
RUN;

DATA REGRESS_2;
SET REGRES_(DROP = USER_ID);
RUN;

PROC STANDARD DATA=REGRESS_2 MEAN=0 STD=1 OUT=ZREGRESS;
VAR MARITAL_STATUS SEX YEARS CITY_CATEGORY_A CITY_CATEGORY_B MEDIAN_AGE;
RUN;

PROC GLM DATA = ZREGRESS;
  CLASS OCCUPATION;
  MODEL TOTAL_AMT
      = SEX CITY_CATEGORY_A CITY_CATEGORY_B MEDIAN_AGE / SOLUTION SS3;
  MANOVA H=_ALL_;
RUN;
QUIT;


/**************************************************************************************/
/**************************************************************************************/
/**************************************************************************************/
/*SLIDE 19 CUSTOMER SEGMENTATION*/

PROC TABULATE DATA=AGGRE;
TITLE 'CUSTOMER PROFILE BY FEATUE SIGNIFICANCE';
CLASS CITY_CATEGORY GENDER;
VAR TOTAL_AMT;
TABLE CITY_CATEGORY ALL ,GENDER *(TOTAL_CUST=' ');
RUN;

PROC TABULATE DATA=AGGRE;
TITLE 'CUSTOMER PROFILE';
CLASS AGE CITY_CATEGORY GENDER;
VAR TOTAL_AMT;
TABLE (CITY_CATEGORY ALL)*(GENDER ALL), AGE='AGE GROUPS'*(PCTN='% ') ALL*(N PCTN);
RUN;


/**************************************************************************************/
/**************************************************************************************/
/**************************************************************************************/
TITLE 'SALES BY CITY CATEGORY FOR DIFFERENT PRODUCTS';

LEGEND1 LABEL=NONE
        SHAPE=BAR(4,1.5)
        POSITION=(MIDDLE LEFT)
        OFFSET=(5,)
        ACROSS=1
        MODE=SHARE;



/**************************************************************************************/
/**************************************************************************************/
/**************************************************************************************/
/*EXTRA GRAPHS*/
 /* GENERATE DONUT CHART */

PROC GCHART DATA=TEST;
   DONUT DIST_PROD/ SUMVAR=PURCHASE
                SUBGROUP=CITY_CATEGORY
                NOHEADING
                DONUTPCT=30
				PERCENT = INSIDE
                LABEL=('BLACK' JUSTIFY=CENTER 'FRIDAY')
                LEGEND=LEGEND1
                COUTLINE=BLACK
                CTEXT=BLACK;
RUN;
QUIT;



/*CUSTOMER WISE PURCHASE*/
ODS GRAPHICS ON;
%THREEPANEL(WORK.AGGRE, TOTAL_AMT)




/*PRODUCT DISTRIBUTION*/
/*CREATE A TABLE AGGREGATED BY DISTINCT PRODUCT COUNTS*/
PROC SQL;
CREATE TABLE PROD_DISTR AS
SELECT DIST_PROD, 
	   COUNT(DISTINCT USER_ID)AS NUMBER_OF_CUST, 
	   SUM(PURCHASE) AS TOTAL_SALES,
	   AVG(PURCHASE) AS AVG_SALES,
	   CITY_CATEGORY
FROM TEST
GROUP BY DIST_PROD, CITY_CATEGORY
;
QUIT;



/*CITY CATEGORY WISE AVERAGE SALES*/

PROC UNIVARIATE DATA=PROD_DISTR;
  CLASS CITY_CATEGORY;
  VAR AVG_SALES;      /* COMPUTES DESCRIPTIVE STATISITCS */
  HISTOGRAM AVG_SALES / NORMAL MIDPOINTS=(0 TO 25000 BY 2500) NROWS=3 ODSTITLE="PURCHASE DISTRIBUTION BY MARITAL STATUS";
  ODS SELECT HISTOGRAM; /* DISPLAY ON THE HISTOGRAMS */
RUN;
QUIT;

PROC MEANS DATA = PROD_DISTR;
RUN;
QUIT;



PROC UNIVARIATE DATA=PROD_DISTR;
TITLE "CITY WISE AVERAGE SALES AMOUNT PER PRODUCT";
  CLASS CITY_CATEGORY;
  VAR TOTAL_SALES;      /* COMPUTES DESCRIPTIVE STATISITCS */
  HISTOGRAM TOTAL_SALES /  NROWS=3 ODSTITLE="CITY WISE TOTAL SALES AMOUNT PER PRODUCT";
  ODS SELECT HISTOGRAM; /* DISPLAY ON THE HISTOGRAMS */
RUN;
QUIT;
/*PRODUCT WISE DISTRIBUTION*/

 /* DEFINE TITLES AND FOOTNOTES */
TITLE1 'AVERAGE PRODUCT-WISE SALES';
FOOTNOTE1 J=L ' ABC PVT LTD';
FOOTNOTE2 ' ';

 /* DEFINE SYMBOL CHARACTERISTICS */
SYMBOL1 INTERPOL=JOIN VALUE=DOT HEIGHT=1.7;  

 /* GENERATE A PLOT OF THREE VARIABLES */
 /* THAT PRODUCES A LEGEND.            */




/* DEFINE THE TITLE FOR THE CHART */
TITLE 'AVERAGE SALES BY CITY FOR DIFFERENT PRODUCTS';

LEGEND1 LABEL=NONE
        SHAPE=BAR(4,1.5)
        POSITION=(MIDDLE LEFT)
        OFFSET=(5,)
        ACROSS=1
        MODE=SHARE;

 /* GENERATE DONUT CHART */
PROC GCHART DATA=PROD_DISTR;
   DONUT DIST_PROD/ SUMVAR=TOTAL_SALES
                SUBGROUP=CITY_CATEGORY
                NOHEADING
                DONUTPCT=30
                LABEL=('BLACK' JUSTIFY=CENTER 'FRIDAY')
                LEGEND=LEGEND1
                COUTLINE=BLACK
                CTEXT=BLACK;
RUN;
QUIT;



ODS LISTING STYLE=LISTING;
ODS GRAPHICS / WIDTH=5IN HEIGHT=2.81IN;

TITLE 'TOTAL SALES BY PRODUCT AND CITY';
PROC SGPLOT DATA=PROD_DISTR(WHERE =(DIST_PROD = '1-15' OR DIST_PROD = '1-2' 
									OR DIST_PROD = '5-5' OR DIST_PROD = '5-8'
									OR DIST_PROD = '8-8'OR DIST_PROD = '6-8'));
  VBAR CITY_CATEGORY / RESPONSE=TOTAL_SALES GROUP=DIST_PROD GROUPDISPLAY=CLUSTER 
    STAT=SUM DATASKIN=GLOSS;
  XAXIS DISPLAY=(NOLABEL NOTICKS);
  YAXIS GRID;
RUN;

ODS LISTING STYLE=LISTING;
ODS GRAPHICS / WIDTH=5IN HEIGHT=2.81IN;

/*BY MARITAL STATUS*/
PROC UNIVARIATE DATA=AGGRE;
  CLASS MARITAL_STATUS;
  VAR TOTAL_AMT;      /* COMPUTES DESCRIPTIVE STATISITCS */
  HISTOGRAM TOTAL_AMT / NROWS=2 ODSTITLE="TOTAL AMOUNT SPENT BY MARITAL STATUS";
  ODS SELECT HISTOGRAM; /* DISPLAY ON THE HISTOGRAMS */
RUN;
QUIT;

PROC UNIVARIATE DATA=AGGRE;
  CLASS CITY_CATEGORY;
  VAR TOTAL_AMT;      /* COMPUTES DESCRIPTIVE STATISITCS */
  HISTOGRAM TOTAL_AMT / NROWS=3 ODSTITLE="TOTAL AMOUNT SPENT BY CITY CATEGORY";
  ODS SELECT HISTOGRAM; /* DISPLAY ON THE HISTOGRAMS */
RUN;
QUIT;








